apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: mong-exp
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    beta.cloud.google.com/backend-config: '{"default": "mong-exp-test"}'
spec:
  selector:
    name: mongo-express
  type: NodePort
  ports:
    - targetPort: 8081
      port: 8081
      nodePort: 32001
      name: node01
      protocol: TCP