apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: mong-exp
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    beta.cloud.google.com/backend-config: '{"default": "web-test"}'
spec:
  selector:
    name: web-pod
  type: NodePort
  ports:
    - name: port0
      protocol: TCP
      nodePort: 32000
      port: 3000
      targetPort: 3000